enum Signal {
  SAVE_BACKUP = 'SAVE_BACKUP',
  RENAME_BACKUP = 'RENAME_BACKUP',
  OPEN_DIRECTORY_DIALOG = 'OPEN_DIRECTORY_DIALOG',
  DELETE_SAVE_FILE = 'DELETE_SAVE_FILE',
  OPEN_FOLDER = 'OPEN_FOLDER',
  OPEN_FILE_DIALOG = 'OPEN_FILE_DIALOG',
  EXE_FILE = 'EXE_FILE',
  MIGRATE_BACKUPS = 'MIGRATE_BACKUPS',
  EXPORT_CONFIG = 'EXPORT_CONFIG',
  IMPORT_CONFIG = 'IMPORT_CONFIG',
}

export default Signal;
